# Generated by Django 3.2.3 on 2021-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_ground',
            name='date',
            field=models.DateField(verbose_name='Y-m-d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Y-m-d'),
        ),
    ]
