# Generated by Django 3.2.3 on 2021-05-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0003_upcoming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcoming',
            old_name='eid',
            new_name='upid',
        ),
    ]
