# Generated by Django 3.2.3 on 2021-05-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0004_rename_eid_upcoming_upid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upcoming',
            new_name='upcoming_events',
        ),
    ]
